name: Rover Terraform Visualization
description: Run Terraform standalone and generate PNG
inputs:
  filename:
    description: Filename for convert SVG to PNG file
    required: false
    default: 'rover.png'
  planPath:
    description: Path to Terraform plan file
    required: false
    default: 'examples/plan.out'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.tfDir }}
    - ${{ inputs.filename }}
