name: Rover Terraform Visualization
description: Run Terraform standalone and generate PNG
inputs:
  directory:
    description: Directory to change to before executing rover
    required: false
    default: examples
  filename:
    description: Filename for convert SVG to PNG file
    required: false
    default: 'rover.png'
  planPath:
    description: Path to Terraform plan file
    required: false
    default: 'plan.out'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.filename }}
    - ${{ inputs.planPath }}
